### ISSUE TITLE
add images to the readme

### ISSUE THREAD

**Issue by shreshthmohan** [balub/CoryDora#2]
- [ ] exploded view
- [ ] each part's photos (rendered & real maybe)

**Comment by balub** [comment]
@shreshthmohan Do you want me to add the image of a raw PCB to the readme ?

**Comment by shreshthmohan** [comment]
A photo of the PCB once it comes back from the manufacturer. Also photos of every part before assembly too (eventually). Maybe add one photo in the beginning & the rest in the end to keep people from being overwhelmed.

Gives one an idea of how the build will go / parts will look.

You should also add a link to the they can buy it

**Comment by shreshthmohan** [comment]
readme is looking so much better now!

maybe add a link to store saying: "too lazy to build one on your own, [get mine](https://shop.absurd.industries/products/cory-dora)!"
